version: '3.7'

services:
  mafia:
    container_name: mafia
    build: .
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - NODE_ENV=production
    labels:
      - 'traefik.docker.network=traefik_proxy'
      - 'traefik.enable=true'
      - 'traefik.port=5000'
      - 'traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}'

networks:
  traefik_proxy:
    external: true
