version: '3.8'

services:
  mafia:
    container_name: ${PROJ_NAME}
    build:
      context: .
    labels:
      - "traefik.http.routers.${PROJ_NAME}.rule=Host(`${REACT_APP_DOMAIN}`)"
      - "traefik.http.routers.${PROJ_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJ_NAME}.tls.certresolver=myresolver"
      - "traefik.http.routers.${PROJ_NAME}.tls.domains[0].main=${REACT_APP_DOMAIN}"
      - "traefik.http.routers.${PROJ_NAME}.tls.domains[0].sans=www.${REACT_APP_DOMAIN}"    

networks:
  default:
    external: 
      name: traefik      