version: '3.7'

services:
  mafia:
    container_name: mafia
    build: .
    restart: unless-stopped
    networks:
      nginx_net:
    environment:
      - NODE_ENV=production

networks:
  nginx_net:
    external: true
