const colors = {
  SeatAllocator: {
    navBarText: '#71B2FE',
    numbersPanel: '#71B2FE',
    number: '#98C8FF',
    numberSelected: '#3E97FE',
    popupBackground: '#3E97FE',
    popupCircleBackground: '#70b2ff',
    popupButton: '#70b2ff',
    popupText: '#3E97FE',
  },
  RoleDealing: {
    navBarText: '#FB6F6F',
    numbersPanel: '#2D2D2D',
    number: '#CBC2B7',
    numberSelected: '#FB6F6F',
    popupBackground: '#373737',
    popupBackgroundLight: '#FB6F6F',
    popupButton: '#484848',
    popupButtonLight: '#FF8282',
    popupText: '#FB6F6F',
    popupTextLight: '#FFD8D8',
    popupIcon: '#686A6E',
    popupIconLight: '#FFD8D8',
    dealingMode: '#818385',
    dealingModeSelected: '#B2B2B2',
  },
  ZeroNight: {
    navBarText: '#FB6F6F',
    numbersPanel: '#2D2D2D',
    number: '#CBC2B7',
    numberSelected: '#FB6F6F',
    popupBackground: '#373737',
    popupBackgroundLight: '#FB6F6F',
    popupButton: '#484848',
    popupButtonLight: '#FF8282',
    popupTextLight: '#FFD8D8',
    popupIcon: '#686A6E',
    popupIconLight: '#FFD8D8',
    popupLabel: '#FB6F6F',
  },
  Day: {
    navBarText: '#E9E1D4',
    numbersPanel: '#E9E1D4',
    number: '#CBC2B7',
    numberSelected: '#6D80AB',
    playerCardBackground: '#EFE8DF',
    playerCardNumber: '#ADB4C2',
    deadPlayerCardBackground: '#4E4E4E',
    deadPlayerCardNumber: '#717171',
    warningPlayerCardBackground: '#FF8888',
    warningPlayerCardNumber: '#686C75',
    activePlayer: '#000',
    playerOpensTable: '#8A8A8A',
    removeFoulBackground: '#D4C7B2',
    addFoulIconBackground: '#8A8A8A',
    addFoulBackground: '#8A8A8A',
    addSecondFoulBackground: '#F28E0C',
    addThirdFoulBackground: '#FB6F6F',
    popupBackground: '#373737',
    popupButton: '#484848',
    popupNightResult: '#F51C1C',
  },

  Voting: {
    navBarText: '#E9E1D4',
    numbersPanel: '#E9E1D4',
    number: '#6D80AB',
    numberSelected: '#759EFF',
    playerCardBackground: '#EFE8DF',
    playerCardNumber: '#ADB4C2',
    deadPlayerCardBackground: '#4E4E4E',
    deadPlayerCardNumber: '#717171',
    warningPlayerCardBackground: '#FF8888',
    warningPlayerCardNumber: '#686C75',
    activePlayer: '#000',
    playerOpensTable: '#3EF538',
    removeFoulBackground: '#D4C7B2',
    addFoulIconBackground: '#8A8A8A',
    addFoulBackground: '#8A8A8A',
    addSecondFoulBackground: '#F28E0C',
    addThirdFoulBackground: '#FB6F6F',
    popupBackground: '#6D80AB',
    popupButton: '#889DCE',
    popupButtonLight: '#F28E0C',
    popupText: '#6D80AB',
    handsAmountBackground: '#fff',
    popupTextInverse: '#fff',
    handsAmountSelectedBackground: '#759EFF',
    handsAmountDisabledBackground: '#435784',
    handsAmountDisabledText: '#7E8CAB',
  },

  EndOfGame: {
    navBarText: '#fff',
    numbersPanel: '#484848',
    number: '#F37F7F',
    numberSelected: '#000',
    popupBackground: '#373737',
    popupBackgroundLight: '#FB6F6F',
    popupButton: '#484848',
    popupButtonLight: '#FF8282',
    popupText: '#fff',
  },
};

colors.Night = {
  ...colors.ZeroNight,
  eyeIconFront: '#ADB4C2',
  eyeIconBack: '#686A6E',
  eyeIconBackDead: '#4E4E4E',
  darkRoleBackground: '#000',
  darkRoleBackgroundDead: '#3E3E3E',
  lightRoleBackground: '#FB6F6F',
  roleText: '#fff',
  roleTextDead: '#717171',
  buttonText: '#636363',
  buttonTextInverse: '#fff',
  handsAmountBackground: '#fff',
  handsAmountSelectedBackground: '#858585',
  handsAmountDisabledBackground: '#444444',
  handsAmountDisabledText: '#4e4e4e',
};

export default colors;
