export default {
  SeatAllocator: {
    navBarText: '#71B2FE',
    numbersPanel: '#71B2FE',
    number: '#98C8FF',
    numberSelected: '#3E97FE',
    popupBackground: '#3E97FE',
    popupCircleBackground: '#70b2ff',
    popupButton: '#70b2ff',
    popupText: '#3E97FE',
  },
  RoleDealing: {
    navBarText: '#FB6F6F',
    numbersPanel: '#2D2D2D',
    number: '#CBC2B7',
    numberSelected: '#FB6F6F',
    popupBackground: '#373737',
    popupBackgroundLight: '#FB6F6F',
    popupButton: '#484848',
    popupButtonLight: '#FF8282',
    popupText: '#FB6F6F',
    popupTextLight: '#FFD8D8',
    popupIcon: '#686A6E',
    popupIconLight: '#FFD8D8',
    dealingMode: '#818385',
    dealingModeSelected: '#B2B2B2',
  },
};
